backend:
  name: git-gateway
  branch: main 
media_folder: "static/images" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Categories", name: "categories", widget: "list"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Featured Image", name: "image", widget: "image"}
      - {label: "Summary", name: "summary", widget: "string"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Draft", name: "draft",  widget: "select", options: ["true", "false"]}
      - {label: "Body", name: "body", widget: "markdown"}